# Generated by Django 2.2.20 on 2021-04-22 17:26

from django.db import migrations


def mark_as_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_auto_20210421_2041'),
    ]

    operations = [
        migrations.RunPython(mark_as_new_building)
    ]
