# Generated by Django 2.2.20 on 2021-04-25 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год постройки здания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
