# Generated by Django 2.2.20 on 2021-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210427_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='ФИО владельца'),
        ),
    ]
