# Generated by Django 2.2.20 on 2021-04-28 18:11

from django.db import migrations, models


def relate_flat_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.full_name)
        owner.estates.set(flats)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0015_auto_20210428_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(db_index=True, max_length=300,
                                   verbose_name='ФИО владельца')),
        migrations.RunPython(relate_flat_to_owners)
    ]
