# Generated by Django 2.2.20 on 2021-04-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
